runtime: nodejs20
env: standard

beta_settings:
  cloud_sql_instances: project-b2fcff48-a0ca-4867-995:southamerica-east1:meu-banco-postgres

env_variables:
  NODE_ENV: "production"
  PERMISSIONS_ENFORCED: "true"
  SLOW_REQUEST_THRESHOLD_MS: "2000"
  API_RATE_LIMIT_MAX: "600"
  ENFORCE_COMPANY_ACCESS: "false"
  CONTA_AZUL_CLIENT_ID: "93gqdtsa9t2892ci4mejv2n90"
  CONTA_AZUL_TOKEN_URL: "https://auth.contaazul.com/oauth2/token"
  PG_SSL: "false"
  CORS_ORIGINS: "https://project-b2fcff48-a0ca-4867-995.rj.r.appspot.com"
  LOG_TO_CONSOLE: "true"
  AUTH_RATE_LIMIT_MAX: "50"
  DB_CONNECT_RETRIES: "10"
  DB_CONNECT_RETRY_DELAY_MS: "2000"
  EVENT_WEBHOOK_URL: ""
  ALLOW_PUBLIC_REGISTER: "false"

  SECRET_MANAGER_ENABLED: "true"
  GCP_PROJECT_ID: "project-b2fcff48-a0ca-4867-995"
  SECRET_JWT_SECRET: "JWT_SECRET"
  SECRET_CONTA_AZUL_CLIENT_SECRET: "CONTA_AZUL_CLIENT_SECRET"
  SECRET_CONTA_AZUL_ACCESS_TOKEN: "CONTA_AZUL_ACCESS_TOKEN"
  SECRET_CONTA_AZUL_REFRESH_TOKEN: "CONTA_AZUL_REFRESH_TOKEN"
  SECRET_DATABASE_URL: "DATABASE_URL"
  SECRET_SIGNATURE_SECRET: "SIGNATURE_SECRET"
  SECRET_EVENT_WEBHOOK_SECRET: "EVENT_WEBHOOK_SECRET"

handlers:
- url: /.*
  script: auto
